name: Deploy Frontend to Railway
on:
  push:
    branches: [ "main" ]
    paths:
      - "frontend/**"
      - ".github/workflows/deploy-frontend.yml"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install Railway
        run: npm i -g @railway/cli
      - name: Deploy Frontend
        working-directory: frontend
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
          RAILWAY_FRONTEND_SERVICE: ${{ secrets.RAILWAY_FRONTEND_SERVICE }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: |
          echo "VITE_API_URL=$VITE_API_URL" >> .env
          railway link --project $RAILWAY_PROJECT_ID --service $RAILWAY_FRONTEND_SERVICE
          railway up --service $RAILWAY_FRONTEND_SERVICE --detach
